# Jekyll configuration for TLE92466ED driver documentation
title: "TLE92466ED Driver"
description: >
  C++23 driver for Infineon TLE92466ED Six-Channel Low-Side Solenoid Driver IC
  with comprehensive SPI interface, current control, and diagnostics support

baseurl: "/hf-tle92466ed-driver"  # GitHub Pages subpath
url: "https://n3b3x.github.io"

# Author and social information
author:
  name: "N3b3x"
  email: "n3b3x@example.com"
  url: "https://github.com/n3b3x"

# Directory configuration
layouts_dir: _config/_layouts
includes_dir: _config/_includes

# Theme and plugins
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-redirect-from
  - jekyll-optional-front-matter

# Navigation settings
nav_next_prev: true

# Markdown and syntax highlighting
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Site settings
timezone: UTC
encoding: utf-8
lang: en

# Just the Docs configuration
search_enabled: true
search:
  heading_level: 3
  previews: 5
  preview_words_before: 10
  preview_words_after: 15
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

# Navigation and UI enhancements
nav_enabled: true
heading_anchors: true
breadcrumbs: true
toc:
  min_level: 2
  max_level: 4

# Callouts for better content presentation
callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: yellow
  tip:
    title: Tip
    color: green
  important:
    title: Important
    color: red
  specification:
    title: Specification
    color: purple

# Visual enhancements
color_scheme: dark
toggle_color_scheme: true
toggle_auto_mode: true

# Auxiliary links with better organization
aux_links:
  "📚 GitHub Repository":
    - "https://github.com/n3b3x/hf-tle92466ed-driver"
  "🐛 Report Issues":
    - "https://github.com/n3b3x/hf-tle92466ed-driver/issues"
  "⭐ Star on GitHub":
    - "https://github.com/n3b3x/hf-tle92466ed-driver/stargazers"
  "📖 API Documentation":
    - "https://n3b3x.github.io/hf-tle92466ed-driver/doxygen/html/"

# Footer customization
footer_content: >
  Built with ❤️ using <a href='https://just-the-docs.github.io/just-the-docs/'>Just the Docs</a> •
  <a href='https://github.com/n3b3x/hf-tle92466ed-driver/blob/main/LICENSE'>Public Domain</a> •
  <a href='https://github.com/n3b3x/hf-tle92466ed-driver'>View on GitHub</a>

# Collections for better organization
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
    sort_by: nav_order

# Just the Docs configuration
just_the_docs:
  # Navigation configuration
  nav_fold: true
  nav_external_links:
    - title: "📚 GitHub Repository"
      url: "https://github.com/n3b3x/hf-tle92466ed-driver"
    - title: "🐛 Issues"
      url: "https://github.com/n3b3x/hf-tle92466ed-driver/issues"
    - title: "📖 API Docs"
      url: "https://n3b3x.github.io/hf-tle92466ed-driver/doxygen/html/"

  # Custom head content
  head_custom: _includes/head_custom.html

  # Custom CSS and JS
  custom_css:
    - assets/css/custom.css
  custom_js:
    - assets/js/custom.js

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - "*.gem"
  - "*.gemspec"
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - _config/doxygen-extensions/
  - include/
  - src/
  - CMakeLists.txt
  - Doxyfile
  - Doxyfile.in

# Include files that are normally excluded
include:
  - _pages
  - assets/

# Enhanced SEO settings
seo:
  type: "SoftwareApplication"
  name: "TLE92466ED Driver"
  description: >
    C++23 driver for Infineon TLE92466ED Six-Channel Low-Side Solenoid Driver IC
    with comprehensive SPI interface, current control, and diagnostics support
  url: "https://n3b3x.github.io/hf-tle92466ed-driver"
  twitter:
    card: "summary_large_image"
    site: "@n3b3x"
  og:
    type: "website"
    locale: "en_US"

# Social media and sharing
social:
  name: "TLE92466ED Driver"
  links:
    - "https://github.com/n3b3x/hf-tle92466ed-driver"
    - "https://github.com/n3b3x"

# Performance optimizations
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: [html, head, body]

# TLE92466ED specific settings
tle92466ed:
  version: "2.0.0"
  branch: "main"
  version_type: "stable"
  ic_specifications:
    manufacturer: "Infineon Technologies"
    part_number: "TLE92466ED"
    channels: 6
    current_range_single: "0-2A"
    current_range_parallel: "0-4A"
    resolution: "15-bit (0.061mA)"
    interface: "SPI (32-bit frames)"
    crc: "CRC-8 (SAE J1850)"
  driver_features:
    language: "C++23"
    hal: "Hardware-agnostic"
    error_handling: "std::expected"
    safety: "noexcept functions"
    dependencies: "None (freestanding)"
  documentation_sections:
    - title: "IC Overview"
      file: "01_IC_Overview.md"
    - title: "SPI Protocol"
      file: "02_SPI_Protocol.md"
    - title: "Register Map"
      file: "03_Register_Map.md"
    - title: "Current Control"
      file: "04_Current_Control.md"
    - title: "Channel Modes"
      file: "05_Channel_Modes.md"
    - title: "Diagnostics"
      file: "06_Diagnostics.md"
    - title: "Driver API"
      file: "07_Driver_API.md"
    - title: "HAL Implementation"
      file: "08_HAL_Implementation.md"
    - title: "Usage Examples"
      file: "09_Usage_Examples.md"
